version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: nataliagaaze/taski_backend
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - static:/app/backend_static
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: nataliagaaze/taski_frontend
    command: sh -c "npm run build && cp -r /app/build/. /frontend_static/"
    volumes:
      - static:/frontend_static
    restart: unless-stopped

  gateway:
    image: nataliagaaze/taski_gateway
    volumes:
      - static:/staticfiles
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    restart: unless-stopped 