services:
  frontend:
    image: lonlait/taski_frontend:latest
    command: sh -c "npm run build && cp -r build/* /frontend_static/ && tail -f /dev/null"
    volumes:
      - static:/frontend_static
    restart: unless-stopped

  backend:
    image: lonlait/taski_backend:latest
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=158.160.70.136,localhost,127.0.0.1,gopto.hopto.org
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - static:/app/backend_static
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13.10
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  gateway:
    image: lonlait/taski_gateway:latest
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  static: 